name: country_api_parser
description: An app designed to perform queries over countries api.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  dartz: ^0.10.0-nullsafety.2
  easy_debounce: ^2.0.0
  flag: ^5.0.0-nullsafety
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_map: ^0.13.1
  freezed_annotation: ^0.14.2
  get_it: ^7.1.3
  http: ^0.13.3
  json_serializable: ^4.1.2
  lint: ^1.5.3
  logger: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.3
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2

flutter:
  uses-material-design: true